import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import {Card} from '@/components/card';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title> Mansa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Mansa</h1>

        <section>
            <h2>Company</h2>
          <p className={styles.description}>
            Name : MANSA GROUP
          </p>
          <p className={styles.description}>
            SIRET : 03459535434
          </p>
          <p className={styles.description}>
            Address: 112 AV DE PARIS 94300 VINCENNES
          </p>
        </section>

        <section className={styles.grid}>
          <h2> Accounts </h2>
          <Card>
            <h3>Account number: 19040061</h3>
            <p>Balance: 1844.23GBP</p>
          </Card>
          <div className={styles.card}>
            <h3>Account number: 19040061</h3>
            <p>Balance: 1844.23GBP</p>
          </div>
          <div className={styles.card}>
            <h3>Account number: 19040061</h3>
            <p>Balance: 1844.23GBP</p>
          </div>
          <div className={styles.card}>
            <h3>Account number: 19040061</h3>
            <p>Balance: 1844.23GBP</p>
          </div>

        </section>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
