import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import {Accounts} from '@/components/Accounts';
import {Header} from '@/components/Header';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title> Mansa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header/>

        <section>
            <h2>Company</h2>
          <p className={styles.description}>
            Name : MANSA GROUP
          </p>
          <p className={styles.description}>
            SIRET : 03459535434
          </p>
          <p className={styles.description}>
            Address: 112 AV DE PARIS 94300 VINCENNES
          </p>
        </section>

        <section className={styles.grid}>
          <h2> Accounts </h2>
          <Accounts/>
        </section>
      </main>
    </div>
  )
}

export default Home
