import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import {Header} from '@/components/Header/Header';
import {AccountsSection} from '@/components/AccountsSection/AccountsSection';
import {CompanySection} from '@/components/CompanySection/CompanySection';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title> Mansa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header/>
        <CompanySection/>
        <AccountsSection/>
      </main>
    </div>
  )
}

export default Home
